### ISSUE TITLE
Creating a Queuing system 

### ISSUE THREAD

**Issue by Exuviax** [Schmoopiie/twitch-irc#22]
Hey Schomoopiie,

Just wondering if in the next update a queing system for handling all chat events, forced under the 100/30 so the bot doesn't get global banned. As you know mods can only send 100 messages in 30 seconds before they are banned from talking for 8 hours, all over twitch. Or maybe a function that could handle this, writes all commands to a list, fires the one at the top of the list every second and deletes it. Works in order? I have been working on a mock up, but everything I have done so far has either failed, or put a really long extended wait time on replies.

**Comment by Schmoopiie** [comment]
Hey @Exuviax!

This is planned but we will release the next version with IRCv3 tags support first with a bunch of new features and fixes. At the moment, I have to work on the documentation while Twitch officially support IRCv3 tags. The current version supports IRCv3 tags, but Twitch might change the data inside the tags so we are not working on this until Twitch officially announce the IRCv3 tags support.

When we are done with this, we planned to split twitch-irc into different modules to make it light and download only what you need to use. You can expect modules such as twitch-irc-oauth, twitch-irc-api, twitch-irc-rates. What you are asking about is planned but we have no ETA.

Thanks!

**Comment by Exuviax** [comment]
Thank you @Schmoopiie
