### ISSUE TITLE
TwitchNotify changed a bit..

### ISSUE THREAD

**Issue by Schmoopiie** [Schmoopiie/twitch-irc#23]
Looks like Twitch modified TwitchNotify a bit, it is now returning how many months in a row a user has been a subscriber and in some cases, in what channel the user subscribed (when a channel is hosting another channel):

``Username just subscribed!``
``Username just subscribed! 4 months in a row!``
``Username just subscribed to xxxx!``
``Username just subscribed to xxxx! 2 months in a row!``

There might be more changes, but twitch-irc still catches subscriptions.

**Comment by Lange** [comment]
:+1:

If there's anything I can to do help implement support for this, let me know.

**Comment by Schmoopiie** [comment]
So far so good, thanks @Lange!
