### ISSUE TITLE
How to check if someone is moderator?

### ISSUE THREAD

**Issue by SmashKazu** [Schmoopiie/twitch-irc#24]
Hey Schmoopiie,

Since you changed a lot of code I don't know how to check if someone is a moderator.
With your old version you could just create an array with the names in it but for some reason this doesn't work anymore.

How do I check if someone is moderator?

**Comment by Schmoopiie** [comment]
Some events return a user object which contains the information you are looking for. If you look at the [chat event listener](https://github.com/Schmoopiie/twitch-irc/wiki/Event:-Chat), it returns the [user object](https://github.com/Schmoopiie/twitch-irc/wiki/User-object). The status of the user is returned as an array inside the user object.

```
client.addListener('chat', function (channel, user, message) {
    if (user.special.indexOf('mod') >= 0) {
        console.log(user.username + ' is a mod.');
    }
});
```

**Comment by SmashKazu** [comment]
Alright, thanks alot :D
