### ISSUE TITLE
2 IRC Connections - Transport Not Attached

### ISSUE THREAD

**Issue by macharborguy** [Schmoopiie/twitch-irc#25]
Background: I am in the process of converting my current twitch IRC bot from node-irc to twitch-irc.  The bot has it's own twitch account, independent of our channel's account.  In addition, i am moving our bots chat management functions to a separate module.

From what I gather, the bot's IRC account wont get messages about other channels hosting us, so I am trying to connect to both our primary IRC account and the Bot's IRC account within our Bot's code.  All bot functions would listen to the bot's account, while hosting alerts (so and so is hosting you for X viewers) would listened for on the primary account.

To ease headaches, I am doing all of my tests in a separate test.js and module.js set of files to not interrupt current bot activity.

Below is the basic code...

**test.js** 
```
  var chatMan = require('path/to/module.js');
  chatMan.init();
```

**module.js**
```
var irc = require('twitch-irc');
var ChatManager = {
  botIRC : null,
  chanIRC : null,
  
  init : function () {
    this.botIRC = new irc.client({ --options/bot account login/channels-- });
    this.chanIRC = new irc.client({ --options/channel account login/channels-- });
  },
  
  connect : function() {
    this.botIRC.connect();
    this.chanIRC.connect();
  }
};

module.exports = ChatManager;
```

The code would simply crash out.
I then wrapped each of the 'new irc.client()' lines in individual Try/Catch blocks.

'this.botIRC = new irc.client()' would run fine

'this.chanIRC = new irc.client()' throws the following error: **Error: Transport console not attached to this instance**

I looked around online and it appears to have something to do with Winston, possibly.  However, this error is only thrown from within this module.  If I move the irc connections to the main 'test.js' file, they dont throw errors and appear to connect properly.

It could just be something I am doing wrong as well, which wouldn't surprise me.

**Comment by Schmoopiie** [comment]
We are aware of issues with Winston, it's causing many transport issues and also override other applications that uses Winston too. This is why in the next version of twitch-irc we created our own logging system instead. You could try using the beta version but keep in mind that we still need to test on different platforms, so it is unstable.

Thanks!

**Comment by macharborguy** [comment]
Thanks, ill check out the beta now.
