### ISSUE TITLE
Twitch API - redirect_uri "Invalid scope requested"

### ISSUE THREAD

**Issue by MrEliasen** [Schmoopiie/twitch-irc#28]
It appears either the twitch api has changed or passport-twitch is not doing what is intended(?).

When I try to authenticate with the twitch api, the ~~callback~~ redirect_uri is url encoded (which makes sense), but this appears to make twitch's api not able to pickup the scopes you request access to.

Example: ``scope=user_read%2Cchannel_read%2Cchannel_subscriptions%2Cchannel_check_subscription``

When I change the ``%2C`` to ``+`` manually it works. The official documentation for the twitch api uses ``+`` as the delimiter instead of ``,`` which could also cause problems.

Or maybe I just missed something completely in the config or like? 

Edit: Also, forgot to mention, thanks for the work you have put into this! Saved me a lot of time so appreciate it! :+1:

**Comment by Schmoopiie** [comment]
Hi @MrEliasen,

Thank you, will definetly look into this. I did a test very quick on our beta but I wasn't able to reproduce it, I will try with the latest version this weekend and will also try with different browsers. I'll do my best to reproduce this error, but I will need some informations, like your Operating System, Node.js (or io.js) version and twitch-irc version. Also, can you post the configuration of your oauth here (without the client id/secret of course) ?

Thank you, glad you like it ;-)

**Comment by MrEliasen** [comment]
Hi @Schmoopiie,

Thanks for the quick reply!
I won't rule out that I might be the cause but in any case, I'll supply what details I can:

OS: Linux/CentOS 6.5
Browser: Chrome (Latest at time of writing)
Platform: NodeJS v0.10.35

Config:
```javascript
oauth: {
    port: 6511,
    clientID: "<client-id>",
    clientSecret: "<secret>",
    scopes: "user_read,channel_read"
}```

If you wish to try it out I've enabled the bot for now: http://bot.sirmre.com:6511/auth/twitch/callback no need to actually authenticate of cause :).

Hope it helps, else if you need more info or if you would like to see the  code, just let me know. The bot will be open sourced in the end anyway :+1: .

**Comment by Schmoopiie** [comment]
Ahhh, I get it.. you have to visit http://bot.sirmre.com:6511/ instead of http://bot.sirmre.com:6511/auth/twitch/callback which is the callback URL. I will make sure to provide this information in the next wiki :smile:

**Comment by MrEliasen** [comment]
Ahh haha! of cause! For crying out loud! :smile:  haha!
For whatever reason I never realised it had "callback" in the url"..

That is it, I need sleep!

Thank you very much for the help :smile:

**Comment by Schmoopiie** [comment]
Also, if it redirects to 127.0.0.1 after authentication, we fixed the redirect url after oauth in the beta version. You have to specify your hostname in the configuration.

Example:

```json
oauth: {
        port: 6511,
        hostname: 'bot.sirmre.com',
        clientID: 'xxxxx',
        clientSecret: 'xxxxx',
        scopes: 'user_read,channel_read'
    }
```

Hopefully we will be able to release a new stable version soon.. I am waiting for Twitch to release IRCv3 tags before releasing it.

**Comment by MrEliasen** [comment]
No worries, I figured I would need to code that bit in myself (I did wonder why it was hard coded).
Makes sense, no worries at all I can just make the amends manually in the meantime :+1:

**Comment by Schmoopiie** [comment]
Alright, have fun! :smile: 

:+1:
