### ISSUE TITLE
Joining an event will not receive messages

### ISSUE THREAD

**Issue by ReidandKat** [Schmoopiie/twitch-irc#29]
If I join an event room (i.e. riotgames) I do not see any chat events:

var irc = require('twitch-irc');

var client = new irc.client({
        options: {
        debug: true,
        debugIgnore: ['ping', 'action'],
        logging: false,
        tc: 3
    },
    identity: {
        username: 'removed',
        password: 'removed'
    },
    channels: [ 'riotgames' ]
});

client.connect();

client.addListener('chat', function (channel, user, message) {
    console.log(message);
});

**Comment by Schmoopiie** [comment]
Hi @ReidandKat!

Sorry if this is undocumented, but Twitch has different servers for group and event channels. In your case, you will have to set ``serverType`` to events, or set the ``preferredServer``/``preferredPort`` to one of the following IP addresses:

- 199.9.250.117 on port 80 or 443
- 199.9.251.213 on port 80 or 443
- 199.9.252.26 on port 80 or 443

Examples:

```javascript
var client = new irc.client({
    options: {
        debug: true,
        debugIgnore: ['ping', 'action'],
        logging: false,
        tc: 3
    },
    connection: {
        serverType: 'events'
    },
    identity: {
        username: 'removed',
        password: 'removed'
    },
    channels: [ 'riotgames' ]
});
```

```javascript
var client = new irc.client({
    options: {
        debug: true,
        debugIgnore: ['ping', 'action'],
        logging: false,
        tc: 3
    },
    connection: {
        preferredServer: '199.9.251.213',
        preferredPort: 443
    },
    identity: {
        username: 'removed',
        password: 'removed'
    },
    channels: [ 'riotgames' ]
});
```
