### ISSUE TITLE
Improve _handleMessage function..

### ISSUE THREAD

**Issue by Schmoopiie** [Schmoopiie/twitch-irc#30]
**EDIT**: A complete rewrite of _handleMessage is needed. Changes will include a better handling of IRCv3 tags and a better handling of TC 1 - 4. Changes may also include a re-write of the commands callback feature. If we can handle everything without using any TC, that would also be awesome.. but this is not a priority.

**Comment by enilsen16** [comment]
Update irc-message to v3.0.0

#35

**Comment by Schmoopiie** [comment]
Merged your PR @enilsen16, I didn't have time to look at the changes made with the v3.0.0 as I am busy with my work, I will this weekend though :smile:

**Comment by Schmoopiie** [comment]
Updated in [92b03b3](https://github.com/Schmoopiie/twitch-irc/commit/92b03b3ed0c0a990e8acfeb6132c6bdf0a828819).. I still need to test everything, then I will push the update and also release the new documentation. Hopefully will release a stable version this week.
