### ISSUE TITLE
Follower Notification

### ISSUE THREAD

**Issue by cleaso** [Schmoopiie/twitch-irc#31]
Hello Developer!
Is there a way in the application to catch New Follower Events?

Kind Regards

**Comment by enilsen16** [comment]
You need to use the API, found here https://github.com/justintv/Twitch-API. 

for example, `https://api.twitch.tv/kraken/channels/kanthes/follows` will return JSON of the last 20 followers ordered by date. I recommend referring to the [Twitch Developer Forums](http://discuss.dev.twitch.tv) if you have questions regarding the api.

**Comment by Schmoopiie** [comment]
@enilsen16 is right, I will close this issue since this is not really related to twitch-irc.
