### ISSUE TITLE
Alias leave to part or vise-versa

### ISSUE THREAD

**Issue by enilsen16** [Schmoopiie/twitch-irc#32]
its confusing, I had to look at the source code to find the method. This should also be changed in the documentation.

**Comment by Schmoopiie** [comment]
Totally agree with you, merged your PR.

Thanks!

**Comment by enilsen16** [comment]
What happens if I call `client.join('schmoopiie);` multiple times? Does the client connect to that channel multiple times? 

```
[17:28:49] chat  - [#eyeswl] eyeswl: !join
[17:28:49] chat  - [#eyeswl] eyeswl: I have successfully joined eyeswl's channel.
[17:28:49] event - join
[17:28:49] raw   - 353: =
[17:28:49] raw   - 366: #eyeswl
[17:28:51] chat  - [#eyeswl] eyeswl: !join
[17:28:51] chat  - [#eyeswl] eyeswl: I have successfully joined eyeswl's channel.
[17:28:51] event - join
[17:28:51] raw   - 353: =
[17:28:51] raw   - 366: #eyeswl
```

It looks like `client.channels` contains the array I'm looking for but it returns undefined if I `console.log` it.

**Comment by enilsen16** [comment]
Looks like to to access the channels array its `client.options.channels`. Which is confusing because as it turns out options is nested in options. 

Here's a piece of what `client.connect();` returns -
```
options: 
   { options: 
      { debug: true,
        debugDetails: true,
        debugIgnore: [Object],
        logging: false,
        chat: true,
        tc: 3 },
```

**Comment by Schmoopiie** [comment]
This is actually something I am working on for the 1.2.0 release.. Most commands will have a callback feature and I still need to work on the join and part commands. The current channels are stored internally in the [Channels](https://github.com/Schmoopiie/twitch-irc/blob/1.1.1b/library/client.js#L43) variable but this is still a work in progress.. I have to make sure a channel is joined before storing it.

You said you had trouble getting the channels option.. I assume you are trying this client-side ? If so, all you have to do is declare the options object outside like this:

```javascript
var irc = require('twitch-irc');

var clientOptions = {
    options: {
        debug: true,
        debugIgnore: ['ping', 'chat', 'action'],
     },
    channels: ['list', 'of', 'channels']
}

var client = new irc.client(clientOptions);

client.connect();

client.addListener('connected', function (address, port) {
    console.log(clientOptions.channels);
});
```
