### ISSUE TITLE
[beta 1.1.18] Crash on startup, undefined is not a function 

### ISSUE THREAD

**Issue by Lange** [Schmoopiie/twitch-irc#35]
Hey there!

I'm trying out the beta (node version 0.12.0, and I'm getting this error:
```
nodecg-0 (out): [22:34:03] error - typeerror: undefined is not a function
nodecg-0 (out):     at linestream.<anonymous> (/home/endofline/nodecg/bundles/lfg-sublistener/node_modules/twitch-irc/library/modules/messages.js:40:23)
nodecg-0 (out):     at linestream.emit (events.js:107:17)
nodecg-0 (out):     at readableaddchunk (_stream_readable.js:163:16)
nodecg-0 (out):     at linestream.readable.push (_stream_readable.js:126:10)
nodecg-0 (out):     at linestream.transform.push (_stream_transform.js:140:32)
nodecg-0 (out):     at linestream._line (/home/endofline/nodecg/bundles/lfg-sublistener/node_modules/twitch-irc/node_modules/lstream/linestream.js:60:8)
nodecg-0 (out):     at /home/endofline/nodecg/bundles/lfg-sublistener/node_modules/twitch-irc/node_modules/lstream/linestream.js:46:10
nodecg-0 (out):     at array.foreach (native)
nodecg-0 (out):     at linestream._transform (/home/endofline/nodecg/bundles/lfg-sublistener/node_modules/twitch-irc/node_modules/lstream/linestream.js:45:9)
nodecg-0 (out):     at linestream.transform._read (_stream_transform.js:179:10)
```

I'm not sure how that function is undefined, as all the appropriate npm deps appear to have installed with no issue.

**Comment by Lange** [comment]
Oh, it seems that in the time between me setting up the first server this morning and the second one this evening, a new version of irc-message was released that changes `parseMessage` to simply `parse`.

**Comment by Schmoopiie** [comment]
There you go.. I also did a version bump for the beta.

**Comment by enilsen16** [comment]
Looks like irc-message had a complete re-write. `parseHostmaskFromPrefix()` was also removed.

**Comment by enilsen16** [comment]
Master will also need this fix as well.

**Comment by expr** [comment]
As the author of irc-message, I encourage you to take a quick look at https://github.com/expr/irc-message/releases/tag/v3.0.0 for information on changes :-)

**Comment by Schmoopiie** [comment]
We will be using your new createStream() and your parser @expr, thanks!
