### ISSUE TITLE
Function callbacks or promises for all commands?

### ISSUE THREAD

**Issue by Dr-Evans** [Schmoopiie/twitch-irc#46]
Hi there.

Are there any plans to integrate function callbacks or promises for all of the commands? For example, when the user sends a clear request, I think it would make sense to have the following syntax:

``` javascript
module.exports.clear = function (req, res) {
    client.clear(req.user.username, function(){
        res.sendStatus(200);
    });
}
```

or 

``` javascript
module.exports.clear = function (req, res) {
    var clearRequest = client.clear(req.user.username);

    clearRequest.then(function () {
        res.sendStatus(200);
    });
}
```

Thanks in advance!

**Comment by enilsen16** [comment]
From #32 -

"This is actually something I am working on for the 1.2.0 release.. Most commands will have a callback feature and I still need to work on the join and part commands."

**Comment by Schmoopiie** [comment]
@enilsen16 is right,

I wanted them to have callbacks but the only way to do it is to wait everytime for JTV to send the message to confirm if it was send or not and if it worked or not.. which is adding a delay for the callback (about 250ms) to fire. When I will rewrite _handleMessage (#30), I will use promises instead, at least there won't be any delay.

**Comment by Schmoopiie** [comment]
Updated in [92b03b3](https://github.com/Schmoopiie/twitch-irc/commit/92b03b3ed0c0a990e8acfeb6132c6bdf0a828819).. I still need to test everything, then I will push the update and also release the new documentation. Hopefully will release a stable version this week.

**Comment by Dr-Evans** [comment]
:+1: :+1: :+1: Nice work @Schmoopiie !!!!
